# 주간 차트 데이터 EDA

In [15]:
## 주간 차트 데이터 컬럼 정제
import pandas as pd

# 1. 차트 데이터 불러오기
df = pd.read_csv("/Users/js/MMA/Melon_Music_Award/data/melon_all_2020_2025.csv")
df.head()

,year,week,rank,title,artist,album,like_cnt
0,2020,12.30~01.05,1,METEOR,창모 (CHANGMO),Boyhood,312714
1,2020,12.30~01.05,2,Psycho,Red Velvet (레드벨벳),‘The ReVe Festival’ Finale,247484
2,2020,12.30~01.05,3,"아마두 (feat.우원재, 김효은, 넉살, Huckleberry P)",염따,Dingo X DAMOIM (Part 2),167122
3,2020,12.30~01.05,4,Blueming,아이유,Love poem,369738
4,2020,12.30~01.05,5,늦은 밤 너의 집 앞 골목길에서,노을,늦은 밤 너의 집 앞 골목길에서,227387

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29400 entries, 0 to 29399
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   year      29400 non-null  int64
 1   week      29400 non-null  object
 2   rank      29400 non-null  int64
 3   title     29400 non-null  object
 4   artist    29400 non-null  object
 5   album     29400 non-null  object
 6   like_cnt  29400 non-null  int64
dtypes: int64(3), object(4)
memory usage: 1.6+ MB

In [17]:
# 중복 확인
df.duplicated().sum()

0

In [18]:
# 통계 확인
df['rank'].describe()

count    29400.000000
mean        50.500000
std         28.866561
min          1.000000
25%         25.750000
50%         50.500000
75%         75.250000
max        100.000000
Name: rank, dtype: float64

In [19]:
# artist 확인
df['artist'].describe()

count     29400
unique      394
top         임영웅
freq       2362
Name: artist, dtype: object

In [27]:
artist_list = df['artist'].unique()
artist_list

array(['창모 (CHANGMO)', 'Red Velvet (레드벨벳)', '염따', '아이유', '노을',
       '백예린 (Yerin Baek)', '백지영', '마마무 (Mamamoo)', 'AKMU (악뮤)', '다비치',
       '장범준', '김나영', '임재현', '마크툽 (MAKTUB)', '정승환', '전상근', '폴킴', '바이브',
       '송하예', 'MC몽', '장덕철', '성시경', '방탄소년단', 'HYNN (박혜원)', '황인욱', 'V.O.S',
       'EXO', '태연 (TAEYEON)', '거미 (GUMMY)', '먼데이 키즈', '볼빨간사춘기', '장혜진',
       '케이시 (Kassy)', 'TWICE (트와이스)', '에이치코드 (H:CODE)', '윤미래',
       '휘인 (Whee In)', 'i-dle (아이들)', '잔나비', '펀치 (Punch)', '10CM',
       '닐로(Nilo)', '벤', 'AOA', '첸 (CHEN)', '신예영', '이우', '빈첸', '박진영',
       '한동근', '헤이즈 (Heize)', '허각', '지코 (ZICO)', '유산슬', '백현 (BAEKHYUN)',
       '윤하 (YOUNHA)', 'pH-1', '정효빈', '우디 (Woody)', '솔라 (마마무)', 'SF9',
       '김재환', '찬열 (CHANYEOL)', '스탠딩 에그', '다이나믹 듀오', '이승철', '가비엔제이', 'KCM',
       '윤건', '송가인', '이해리 (다비치)', '양다일', '혁오 (HYUKOH)', '여자친구 (GFRIEND)',
       '김세정', 'Crush', '청하', '문별 (마마무)', '가호 (Gaho)', '한요한',
       'IZ*ONE (아이즈원)', '김필', '이예준', '진민호', '씨야', '개코', '오반(OVAN)',
       '하현우 (국카스텐)', '임영웅', '육성재', 'ITZY (있지)', 'V', 'NCT 127', '영탁',
       '윤딴딴', '엠씨더맥스 (M.C the MAX)', 'WINNER', '조이 (JOY)', '버스커 버스커',
       '임한별', 'HIGH4 (하이포)', '조정석', '수호 (SUHO)', '로꼬', '규현 (KYUHYUN)',
       '권진아', 'Apink (에이핑크)', '어반자카파', '곽진언', '펭수', '오마이걸 (OH MY GIRL)',
       'NCT DREAM', '에이프릴 (APRIL)', '길구봉구', 'DAY6 (데이식스)', 'Raiden',
       '수퍼비 (SUPERBEE)', '전미도', '미도와 파라솔', '투모로우바이투게더', '비',
       '제이레빗(J Rabbit)', '로이킴', '식케이 (Sik-K)', '런치', '블루 (BLOO)', '백아연',
       '이선희', 'BLACKPINK', '세븐틴 (SEVENTEEN)', '화사 (HWASA)', '선미',
       '신용재 (2F)', '샘김 (Sam Kim)', '김호중', '레드벨벳-아이린&슬기',
       '싹쓰리 (유두래곤, 린다G, 비룡)', 'ASH ISLAND', '지아', '세훈&찬열', '이수현', '솔지',
       '주시크 (Joosiq)', '이하이', '산들', '전소미', '린다G', '제시 (Jessi)', '비룡',
       '유두래곤', '이상순', 'GRAY (그레이)', '로시 (Rothy)', 'DAY6 (Even of Day)',
       '카더가든', '유아 (오마이걸)', '순순희', '정은지', '환불원정대', '기리보이', '에일리(Ailee)',
       '경서예지', '임창정', 'NCT U', 'XIA (준수)', '적재', 'MINO (송민호)',
       '에릭남 (Eric Nam)', '이승기', '경서', '미란이 (MIRANI)',
       '코드 쿤스트 (CODE KUNST)', '릴보이 (lIlBOI)', '스윙스', '허성현 (rosy)',
       'aespa', 'Khundi Panda', '양요섭', '원슈타인', '머쉬베놈 (MUSHVENOM)',
       '래원 (Layone)', '나얼', 'SG 워너비', '#안녕', '마미손', '윤도 (YoonDo)', '송이한',
       '이수 (엠씨더맥스)', '에픽하이 (EPIK HIGH)', '현아', '원경서', '정동하', '라비 (RAVI)',
       'SHINee (샤이니)', '이소정', '죠지', '브레이브걸스', '린', '로제 (ROSÉ)',
       'CHEEZE (치즈)', '이루', '호미들', '웬디 (WENDY)', '황치열', '박재범',
       'STAYC(스테이씨)', '하동균',
       'MSG워너비 TOP 8 (별루지, 김정수, 강창모, 정기석, 이동휘, 이상이, 박재정, 원슈타인)',
       '라붐 (LABOUM)', 'MSG워너비(정상동기)', 'MSG워너비(M.O.M)', 'NS 윤지', '반하나',
       '이무진', 'Seori', '빅마마', '디핵 (D-Hack)', '김대명', 'MSG워너비', '유연석', '효린',
       '정경호', '피아노맨', '케이윌', '멜로망스', '윤토벤', '최유리', 'B.I',
       '아넌딜라이트(Anandelight)', '2am', '이영지', 'Don Mills', "BE'O (비오)",
       'sokodomo', '진', '조광일', '베이식 (Basick)', 'KOONTA (쿤타)', 'SINCE',
       'Mudd the student', 'IVE (아이브)', '김민석 (멜로망스)', 'GOT the beat',
       '비비 (BIBI)', '토요태', '존박', '이승윤', '탑현', 'YENA (최예나)', '쿠기 (Coogie)',
       'Kep1er (케플러)', 'TOIL', '프로미스나인', '선예', '마크 (MARK)', '잠골버스', '정국',
       '비투비', '태일 (TAEIL)', '박봄 (Park Bom)', '김태리', 'NMIXX', '자우림',
       '조현아 (어반자카파)', '하이라이트 (HIGHLIGHT)', '주호', 'BIGBANG (빅뱅)',
       '윤민수(바이브)', 'BIG Naughty (서동현)', '싸이 (PSY)', '지민',
       '릴러말즈 (Leellamarz)', 'LE SSERAFIM (르세라핌)', 'WSG워너비 조별경연 (대청봉)',
       'WSG워너비', '나연 (TWICE)', 'PATEKO (파테코)', 'WSG워너비 (가야G)',
       'WSG워너비(4FIRE)', 'WSG워너비 (오아시소)', '이석훈', '딘딘 (DINDIN)', '김승민',
       'NewJeans', "소녀시대 (GIRLS' GENERATION)", '보라미유', '우원재', '21학번',
       '츄 (CHUU)', '시온', '테이', '강민경 (다비치)', '이영현', '백아', '유림', '카라',
       '저스디스 (JUSTHIS)', '그루비룸 (GroovyRoom)', 'RM', '노윤하',
       '던말릭 (DON MALIK)', 'KHAN', 'NSW yoon', '태양', '몬스타엑스', '김연지',
       '순순희(기태)', '부석순 (SEVENTEEN)', 'DK(디셈버)', 'H1-KEY (하이키)',
       '포맨 (4MEN)', 'Zior Park', 'j-hope', '주주 시크릿', '지수 (JISOO)',
       '이홍기 (FT아일랜드)', 'Agust D', 'Say Yes!', 'FIFTY FIFTY', '던 (DAWN)',
       'NCT 도재정', '박재정', '이채연', 'Stray Kids (스트레이 키즈)', '제이세라',
       '빈지노 (Beenzino)', 'ZEROBASEONE (제로베이스원)', 'Paul Blanco', '우효',
       '권은비', '이세계아이돌', '미연 (MIYEON)', 'RIIZE', '허용별 (허각, 신용재, 임한별)',
       '도경수(D.O.)', '제니 (JENNIE)', 'dori', 'Yyeon', '범진',
       '너드커넥션 (Nerd Connection)', 'DEAN', 'QWER', 'PLAVE', 'VIVIZ (비비지)',
       'Sondia', '안세하', '화곡동 청개구리', 'TWS (투어스)', '이창섭', '아일릿(ILLIT)',
       'LUCY', 'KISS OF LIFE', 'BABYMONSTER', '도영 (DOYOUNG)', '순순희(지환)',
       '이클립스 (ECLIPSE)', '유회승 (엔플라잉)', 'tripleS (트리플에스)', '민니 (MINNIE)',
       '엔플라잉 (N.Flying)', '에스파파(S.Papa.)', 'BOYNEXTDOOR', 'MEOVV (미야오)',
       '조장혁', 'WOODZ', 'G-DRAGON', '황가람', '재쓰비 (JAESSBEE)', '박효신',
       '김보경 (NEON)', '조째즈', 'KiiiKiii (키키)', 'Hearts2Hearts (하츠투하츠)',
       '이예은', '송필근', 'RESCENE (리센느)', 'NCT WISH', '현서 (HYUN SEO)',
       '마틴스미스', '데이먼스 이어 (Damons year)', 'ALLDAY PROJECT', '거북이', '이찬혁',
       '박다혜', 'CORTIS (코르티스)', '다영 (DAYOUNG)', '브라운 아이드 소울', '한로로', '나윤권',
       '이보람 (씨야)', '아샤트리', '노아주다 (noahjooda)', '2BIC(투빅)', '김진표'],
      dtype=object)

## 심사대상
2024.10.31~2025.11.19 발매된 모든 음원  
각 부문별 음원 점수 집계  
단, 트랙제로 초이스 부문은 심사 기간 상이하고 핫트렌드 부문은 발매 시기 제약 없음

## 주간차트 랭크로 성적 변환

주요 지표 선정  
1위 횟수,
top10 횟수,

In [28]:
artist_summary = df.groupby(['year','artist']).agg(
    best_rank = ('rank', 'min'),           # 최고 순위
    top10_count = ('rank', lambda x: (x <= 10).sum()),  # TOP10 횟수
    chart_in_count = ('rank', 'count'),    # 차트 진입 횟수
    total_likes = ('like_cnt', 'sum')      # 총 좋아요
).reset_index()

In [29]:
artist_summary

     year         artist  best_rank  top10_count  chart_in_count  total_likes
0    2020            #안녕         76            0               3       331643
1    2020           10CM         53            0              16      1400539
2    2020      AKMU (악뮤)          9            2              57     26418760
3    2020            AOA         68            0               7       329840
4    2020     ASH ISLAND         64            0               8       798656
..    ...            ...        ...          ...             ...          ...
901  2025         프로미스나인          8            1              75      5617585
902  2025            한로로         10            1              15      1669278
903  2025  현서 (HYUN SEO)         81            0               7       314160
904  2025     화사 (HWASA)          1           10              11      1290368
905  2025            황가람          3           26              94      9805400

[906 rows x 6 columns]