# 주간 차트 데이터 EDA

In [5]:
## 주간 차트 데이터 컬럼 정제

import pandas as pd

# 1. 차트 데이터 불러오기
df = pd.read_csv("/Users/js/MMA/Melon_Music_Award/data/melon_2024_2025_v1.csv")
df.head()

,연도,시작일,종료일,주차,순위,곡명,아티스트,앨범,좋아요,이미지URL
0,NaN,NaN,NaN,12.30~01.05,1.0,"HOME SWEET HOME (feat. 태양, 대성)",G-DRAGON,"HOME SWEET HOME (feat. 태양, 대성)",229262.0,https://cdnimg.melon.co.kr/cm2/album/images/11...
1,NaN,NaN,NaN,12.30~01.05,2.0,APT.,로제 (ROSÉ),APT.,220476.0,https://cdnimg.melon.co.kr/cm2/album/images/11...
2,NaN,NaN,NaN,12.30~01.05,3.0,Whiplash,aespa,Whiplash - The 5th Mini Album,152143.0,https://cdnimg.melon.co.kr/cm2/album/images/11...
3,NaN,NaN,NaN,12.30~01.05,4.0,나는 반딧불,황가람,나는 반딧불,158171.0,https://cdnimg.melon.co.kr/cm2/album/images/11...
4,NaN,NaN,NaN,12.30~01.05,5.0,toxic till the end,로제 (ROSÉ),rosie,151638.0,https://cdnimg.melon.co.kr/cm2/album/images/11...

In [3]:
df.shape

(5304, 10)

In [4]:
df.groupby(['연도', '주차']).size()

연도    주차
2024  01.01~01.07    51
      01.08~01.14    51
      01.15~01.21    51
      01.22~01.28    51
      01.29~02.04    51
                     ..
2025  12.01~12.07    51
      12.08~12.14    51
      12.15~12.21    51
      12.22~12.28    51
      12.30~01.05    51
Length: 104, dtype: int64

In [11]:
df['시작일'] = df['연도'].astype(str) + '.' + df['주차'].str.split('~').str[0].str.strip()
df['마감일'] = df['마감일_문자열']
df.drop(columns='마감일_문자열', inplace=True)
df.head()

,연도,주차,순위,곡명,아티스트,앨범,좋아요,이미지URL,마감일,시작일
0,2024,10.28~11.03,1.0,APT.,로제 (ROSÉ),APT.,219309,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28
1,2024,10.28~11.03,2.0,Whiplash,aespa,Whiplash - The 5th Mini Album,150132,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28
2,2024,10.28~11.03,3.0,UP (KARINA Solo),aespa,SYNK : PARALLEL LINE - Special Digital Single,117304,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28
3,2024,10.28~11.03,4.0,Mantra,제니 (JENNIE),Mantra,79619,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28
4,2024,10.28~11.03,5.0,HAPPY,DAY6 (데이식스),Fourever,208315,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28

In [12]:
df.to_csv('mma_2025.csv',index=False, encoding="utf-8-sig")

### 1. 곡별 집계
1위=100점 ... 100위=1점 으로 계산  
기간별 곡의 누적점수 집계

In [14]:
## 주간 차트 데이터 EDA

import pandas as pd

# 1. 차트 데이터 불러오기
df = pd.read_csv("mma_2025.csv")

# 2. 순위를 숫자형으로 변환 및 점수 계산 (1위 100점 ~ 100위 1점)
df['순위'] = pd.to_numeric(df['순위'])
df['점수'] = 101 - df['순위']

df.head()

,연도,주차,순위,곡명,아티스트,앨범,좋아요,이미지URL,마감일,시작일,점수
0,2024,10.28~11.03,1.0,APT.,로제 (ROSÉ),APT.,219309,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28,100.0
1,2024,10.28~11.03,2.0,Whiplash,aespa,Whiplash - The 5th Mini Album,150132,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28,99.0
2,2024,10.28~11.03,3.0,UP (KARINA Solo),aespa,SYNK : PARALLEL LINE - Special Digital Single,117304,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28,98.0
3,2024,10.28~11.03,4.0,Mantra,제니 (JENNIE),Mantra,79619,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28,97.0
4,2024,10.28~11.03,5.0,HAPPY,DAY6 (데이식스),Fourever,208315,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28,96.0

In [15]:
# 3. 곡별 집계
# 누적점수, 1위 횟수, TOP 10(1~10위) 횟수, 전체 차트인 주수를 계산합니다.
analysis = df.groupby(['곡명', '아티스트']).agg(
    누적점수=('점수', 'sum'),
    일위횟수=('순위', lambda x: (x == 1).sum()),
    TOP10횟수=('순위', lambda x: (x <= 10).sum()),
    총차트인주수=('순위', 'count')
).reset_index()

analysis['누적점수'] = analysis['누적점수'].map(int)

# 4. 결과 정렬 (누적 점수 기준)
analysis = analysis.sort_values(by='누적점수', ascending=False)

# 5. 상위 20개 출력
print("2025 심사기간 차트 성적 TOP 20:")
print(analysis.head(20).to_string(index=False))

# 6. 결과 저장
# analysis.to_csv("chart_pure_analysis_2025.csv", index=False, encoding="utf-8-sig")

2025 심사기간 차트 성적 TOP 20:
                                        곡명                    아티스트  누적점수  일위횟수  TOP10횟수  총차트인주수
                                  Drowning                   WOODZ  5139     2       46      55
                                  Whiplash                   aespa  5102     0       41      55
                                    나는 반딧불                     황가람  4885     0       31      55
                                      APT.               로제 (ROSÉ)  4836     4       26      55
            HOME SWEET HOME (feat. 태양, 대성)                G-DRAGON  4796    10       28      52
                                     HAPPY             DAY6 (데이식스)  4777     0       16      55
                          내게 사랑이 뭐냐고 물어본다면                     로이킴  4492     0        7      55
                                       천상연                     이창섭  4377     0        0      55
                                       소나기          이클립스 (ECLIPSE)  4374     0        0      55
                             한 페이지가 될 수 있게             DAY6 (데이식스)  4363     0        0      55
                       Welcome to the Show             DAY6 (데이식스)  4190     0        4      55
                 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지               AKMU (악뮤)  4090     0        1      55
                                 Supernova                   aespa  4045     0        3      55
                                       예뻤어             DAY6 (데이식스)  3951     0        0      55
                        toxic till the end               로제 (ROSÉ)  3925     0       10      50
                                      청춘만화                     이무진  3923     0        0      55
                          모르시나요(PROD.로코베리)                     조째즈  3790     0       34      41
                            오늘만 I LOVE YOU             BOYNEXTDOOR  3758     0       15      46
                               REBEL HEART               IVE (아이브)  3723     2       17      45
그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection)) 너드커넥션 (Nerd Connection)  3614     0        0      55

### 2. 아티스트 통합 점수

아티스트의 모든 노래 통합 점수

In [10]:
artist_score = analysis.groupby('아티스트')['누적점수'].sum().sort_values(ascending=False)
artist_score.head(20)

아티스트
DAY6 (데이식스)       20405
aespa             17585
G-DRAGON          15771
IVE (아이브)         11325
이무진               10380
로제 (ROSÉ)          9837
QWER               8339
NewJeans           8150
아이유                7829
황가람                6905
임영웅                6900
제니 (JENNIE)        5577
BOYNEXTDOOR        5551
이창섭                5370
WOODZ              5149
아일릿(ILLIT)         4844
로이킴                4839
우디 (Woody)         4428
이클립스 (ECLIPSE)     4374
PLAVE              4138
Name: 누적점수, dtype: int64

### 3. 점수효율성
점수 효율성 = 누적 점수 ÷ 총 차트인 곡 수

In [15]:
# 아티스트별 곡 수 계산
artist_song_count = analysis.groupby('아티스트')['곡명'].count()

# artist_song_count.sort_values(ascending=False)
# # 효율성 계산 (점수 / 곡 수)
efficiency = (artist_score / artist_song_count).sort_values(ascending=False)

print("아티스트별 곡당 평균 화력(효율성) TOP 10:")
print(efficiency.head(10))

아티스트별 곡당 평균 화력(효율성) TOP 10:
아티스트
이클립스 (ECLIPSE)             4374.0
조째즈                        3790.0
너드커넥션 (Nerd Connection)    3614.0
순순희(지환)                    3463.0
황가람                        3452.5
로제 (ROSÉ)                  3279.0
BABYMONSTER                3076.0
10CM                       3069.0
잔나비                        2979.0
임재현                        2915.0
dtype: float64

# 4. 아티스트 확인

In [16]:
df.head()

,연도,주차,순위,곡명,아티스트,앨범,좋아요,이미지URL,마감일,시작일,점수
0,2024,10.28~11.03,1.0,APT.,로제 (ROSÉ),APT.,219309,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28,100.0
1,2024,10.28~11.03,2.0,Whiplash,aespa,Whiplash - The 5th Mini Album,150132,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28,99.0
2,2024,10.28~11.03,3.0,UP (KARINA Solo),aespa,SYNK : PARALLEL LINE - Special Digital Single,117304,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28,98.0
3,2024,10.28~11.03,4.0,Mantra,제니 (JENNIE),Mantra,79619,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28,97.0
4,2024,10.28~11.03,5.0,HAPPY,DAY6 (데이식스),Fourever,208315,https://cdnimg.melon.co.kr/cm2/album/images/11...,2024.11.03,2024.10.28,96.0

In [24]:
artist_list = df['아티스트'].unique()
len(artist_list)

110

In [23]:
artist_list

array(['로제 (ROSÉ)', 'aespa', '제니 (JENNIE)', 'DAY6 (데이식스)', 'G-DRAGON',
       'QWER', 'AKMU (악뮤)', '프로미스나인', '로이킴', '이클립스 (ECLIPSE)', 'NewJeans',
       '이창섭', '이영지', 'i-dle (아이들)', '순순희(지환)', 'KISS OF LIFE',
       'TWS (투어스)', '아이유', '아일릿(ILLIT)', '너드커넥션 (Nerd Connection)', '잔나비',
       '성시경', '이무진', 'PLAVE', '임영웅', '박재정', '임재현', '세븐틴 (SEVENTEEN)',
       '경서예지', '폴킴', 'IVE (아이브)', 'Crush', '지코 (ZICO)', '범진', 'NMIXX',
       'WOODZ', '정국', '김민석 (멜로망스)', '멜로망스', '태연 (TAEYEON)', 'RIIZE',
       '윤하 (YOUNHA)', '부석순 (SEVENTEEN)', '우디 (Woody)', '황인욱', '허각',
       '방탄소년단', '황가람', 'LE SSERAFIM (르세라핌)', 'MEOVV (미야오)', 'YENA (최예나)',
       '비비 (BIBI)', '카더가든', '최유리', '비투비', 'BABYMONSTER', '재쓰비 (JAESSBEE)',
       'EXO', 'SG 워너비', '순순희', '정승환', '박효신', 'TWICE (트와이스)',
       'BOYNEXTDOOR', 'BIGBANG (빅뱅)', '마크툽 (MAKTUB)', '여자친구 (GFRIEND)',
       '김보경 (NEON)', '조째즈', '지수 (JISOO)', 'KiiiKiii (키키)',
       'Hearts2Hearts (하츠투하츠)', '10CM', 'j-hope', '오반(OVAN)', '이예은',
       '송필근', 'HIGH4 (하이포)', '버스커 버스커', 'RESCENE (리센느)', '로꼬', 'NCT WISH',
       '마크 (MARK)', '현서 (HYUN SEO)', '투모로우바이투게더', '도경수(D.O.)', '마틴스미스',
       '엔플라잉 (N.Flying)', '데이먼스 이어 (Damons year)', 'ALLDAY PROJECT',
       'FIFTY FIFTY', 'BLACKPINK', 'H1-KEY (하이키)', 'NCT DREAM', '거북이',
       '먼데이 키즈', '이찬혁', '박다혜', '임창정', 'DK(디셈버)', 'CORTIS (코르티스)',
       '다영 (DAYOUNG)', '브라운 아이드 소울', '다비치', '화사 (HWASA)', '한로로',
       'BIG Naughty (서동현)', 'AOA', '나윤권', '이보람 (씨야)'], dtype=object)